apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth.example.com
spec:
  dnsNames:
    - auth.example.com
  secretName: auth.example.com
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
