apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-django-forward

commonLabels:
  kustomize.component: traefik-django-forward

resources:
  - certificate.yaml
  - deployment.yaml
  - ingress-route.yaml
  - issuer.yaml
  - middleware.yaml
  - service.yaml

secretGenerator:
  - name: traefik-django-forward-auth-config
    files:
      - config.json
